Repository rcastelo/GSVA, pull requests merged in 2024-04, with the labels that each got.

#159 157 provide filtered gene sets sizes
  NAMESPACE
  R/AllGenerics.R
  R/GSVA-package.R
  R/gsvaNewAPI.R
  R/utils.R
  inst/unitTests/test_inputdatacontainers.R
  man/geneSets.Rd
Labels: feature request

#161 fix WARNING Missing link or links in documentation object 'gsva.Rd': …
  DESCRIPTION
  R/gsvaNewAPI.R
  man/gsva.Rd
Labels: bug

#162 modify vignette to demonstrate use of 'geneSetSizes()' in limma example
  DESCRIPTION
  vignettes/GSVA.Rmd
Labels: feature request

#163 158 load gmt files dealing duplicated gene sets
  DESCRIPTION
  NAMESPACE
  R/GSVA-package.R
  R/gsvaNewAPI.R
  man/deduplicateGeneSets.Rd
  man/readGMT.Rd
Labels: feature request

#164 Optimization in R code of .fastRndWalk()
  DESCRIPTION
  NAMESPACE
  R/gsva.R
  inst/unitTests/test_ssgsea.R
Labels: enhancement
