Repository rcastelo/GSVA, pull requests merged in 2024-08, with the labels that each got.

#181 144 running gsva without kernel density estimation on a dgcmatrix coerces to a dense matrix
  R/AllClasses.R
  R/ecdfvals.R
  R/gsva.R
  R/gsvaNewAPI.R
  R/gsvaParam.R
  inst/unitTests/test_sparse.R
  man/gsvaParam-class.Rd
  src/ecdfvals.c
  src/ks_test.c
  src/register_cmethods.c
  src/utils.c
Labels: enhancement

#182 177 improve annotation mapping through readgmt
  R/GsvaMethodParam.R
  R/gsvaNewAPI.R
  R/utils.R
  man/deduplicateGeneSets.Rd
  man/readGMT.Rd
Labels: bug, enhancement

#183 fix docs and imports as necessary for the new version of readGMT()
  DESCRIPTION
  NAMESPACE
  R/AllClasses.R
  R/GSVA-package.R
  R/gsvaNewAPI.R
  man/readGMT.Rd
Labels: bug

#194 add annotation mapping for SummarizedExperiment and subclasses
  R/AllGenerics.R
  R/GsvaMethodParam.R
  R/gsvaNewAPI.R
Labels: enhancement
